language: java
sudo: false

jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: "dperezcabrera-github"
    token:
      secure: ${SONARCLOUD_TOKEN}
      
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2"
  - '$HOME/.sonar/cache'
  
notifications:
  email:
  - dperezcabrera@gmail.com

env:
  global:
    - GIT_DEPENDENCIES=""
    - GH_USERNAME=dperezcabrera
    - GH_REPO=dperezcabrera/sconf4j

